# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vade-mel <vade-mel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/12/23 16:53:26 by vade-mel          #+#    #+#              #
#    Updated: 2025/12/23 16:53:28 by vade-mel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	= libft.a
CC		= cc
FLAGS	= -Wall -Wextra -Werror -c -g3
INCLUDE	= include

SRC	= ${addprefix src/, \
			ft_atoi.c \
			ft_bzero.c \
			ft_calloc.c \
			ft_isalnum.c \
			ft_isalpha.c \
			ft_isascii.c \
			ft_isdigit.c \
			ft_isprint.c \
			ft_itoa.c \
			ft_memchr.c \
			ft_memcmp.c \
			ft_memcpy.c \
			ft_memmove.c \
			ft_memset.c \
			ft_putchar_fd.c \
			ft_putendl_fd.c \
			ft_putnbr_fd.c \
			ft_putstr_fd.c \
			ft_read_all.c \
			ft_split.c \
			ft_strchr.c \
			ft_strdup.c \
			ft_striteri.c \
			ft_strjoin.c \
			ft_strlcat.c \
			ft_strlcpy.c \
			ft_strlen.c \
			ft_strmapi.c \
			ft_strncmp.c \
			ft_strnstr.c \
			ft_strrchr.c \
			ft_strtrim.c \
			ft_substr.c \
			ft_tolower.c \
			ft_toupper.c \
		}
OBJ	= ${SRC:src/%.c=obj/%.o}

all: ${NAME}
${NAME}: ${OBJ}
	@ar rcs ${NAME} ${OBJ}

obj/%.o: src/%.c
	@mkdir -p obj
	@${CC} ${FLAGS} -I ${INCLUDE} $< -o $@
	@printf "Compiling ${notdir $@}\n"

clean:
	@rm -rf obj
	@printf "Deleting object files\n"

fclean: clean
	@rm -f ${NAME}
	@printf "Deleting ${NAME}\n"

re: fclean all

.PHONY: all bonus clean fclean re
